///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeePassApplicationTest.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateDatabase recording.
    /// </summary>
    [TestModule("0dd837b0-f40a-466f-9260-63a73fa9747a", ModuleType.Recording, 1)]
    public partial class CreateDatabase : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::KeePassApplicationTest.KeePassApplicationTestRepository repository.
        /// </summary>
        public static global::KeePassApplicationTest.KeePassApplicationTestRepository repo = global::KeePassApplicationTest.KeePassApplicationTestRepository.Instance;

        static CreateDatabase instance = new CreateDatabase();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateDatabase()
        {
            varFileName = "/storage/emulated/0/keepass/keepassNewFile1.kdb";
            varPassword = "rx";
            varKey = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateDatabase Instance
        {
            get { return instance; }
        }

#region Variables

        string _varFileName;

        /// <summary>
        /// Gets or sets the value of variable varFileName.
        /// </summary>
        [TestVariable("262ed79b-dcc5-4d1a-80ef-6725d7f76cd9")]
        public string varFileName
        {
            get { return _varFileName; }
            set { _varFileName = value; }
        }

        string _varPassword;

        /// <summary>
        /// Gets or sets the value of variable varPassword.
        /// </summary>
        [TestVariable("295dd481-f48f-4a56-95b5-ecd16ed30843")]
        public string varPassword
        {
            get { return _varPassword; }
            set { _varPassword = value; }
        }

        string _varKey;

        /// <summary>
        /// Gets or sets the value of variable varKey.
        /// </summary>
        [TestVariable("cc936581-76d3-4694-b245-04c890b3e45e")]
        public string varKey
        {
            get { return _varKey; }
            set { _varKey = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.CreateDatabase.FileFilename' at Center", repo.ComAndroidKeepass.CreateDatabase.FileFilenameInfo, new RecordItemIndex(0));
            repo.ComAndroidKeepass.CreateDatabase.FileFilename.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varFileName' on item 'ComAndroidKeepass.CreateDatabase.FileFilename'.", repo.ComAndroidKeepass.CreateDatabase.FileFilenameInfo, new RecordItemIndex(1));
            repo.ComAndroidKeepass.CreateDatabase.FileFilename.Element.SetAttributeValue("Text", varFileName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.CreateDatabase.CreateButton' at Center", repo.ComAndroidKeepass.CreateDatabase.CreateButtonInfo, new RecordItemIndex(2));
            repo.ComAndroidKeepass.CreateDatabase.CreateButton.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varPassword' on item 'ComAndroidKeepass.CreateDatabase.PassPassword'.", repo.ComAndroidKeepass.CreateDatabase.PassPasswordInfo, new RecordItemIndex(3));
            repo.ComAndroidKeepass.CreateDatabase.PassPassword.Element.SetAttributeValue("Text", varPassword);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varPassword' on item 'ComAndroidKeepass.CreateDatabase.PassConfPassword'.", repo.ComAndroidKeepass.CreateDatabase.PassConfPasswordInfo, new RecordItemIndex(4));
            repo.ComAndroidKeepass.CreateDatabase.PassConfPassword.Element.SetAttributeValue("Text", varPassword);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varKey' on item 'ComAndroidKeepass.CreateDatabase.PassKeyfile'.", repo.ComAndroidKeepass.CreateDatabase.PassKeyfileInfo, new RecordItemIndex(5));
            repo.ComAndroidKeepass.CreateDatabase.PassKeyfile.Element.SetAttributeValue("Text", varKey);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.CreateDatabase.ButtonOk' at Center", repo.ComAndroidKeepass.CreateDatabase.ButtonOkInfo, new RecordItemIndex(6));
            repo.ComAndroidKeepass.CreateDatabase.ButtonOk.Touch();
            Delay.Milliseconds(300);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
