///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeePassApplicationTest.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginActivity recording.
    /// </summary>
    [TestModule("c79dd986-52d7-4abf-ae81-2413270dd176", ModuleType.Recording, 1)]
    public partial class LoginActivity : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::KeePassApplicationTest.KeePassApplicationTestRepository repository.
        /// </summary>
        public static global::KeePassApplicationTest.KeePassApplicationTestRepository repo = global::KeePassApplicationTest.KeePassApplicationTestRepository.Instance;

        static LoginActivity instance = new LoginActivity();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginActivity()
        {
            varPassword = "rx";
            VarKey = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginActivity Instance
        {
            get { return instance; }
        }

#region Variables

        string _varPassword;

        /// <summary>
        /// Gets or sets the value of variable varPassword.
        /// </summary>
        [TestVariable("8cc3fb4f-f63d-48dc-a634-f56ae0c2bc90")]
        public string varPassword
        {
            get { return _varPassword; }
            set { _varPassword = value; }
        }

        string _VarKey;

        /// <summary>
        /// Gets or sets the value of variable VarKey.
        /// </summary>
        [TestVariable("69b26953-a7c8-4d9b-acf2-860cbe8b6a23")]
        public string VarKey
        {
            get { return _VarKey; }
            set { _VarKey = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.LogInActivity.FileToSelect' at Center", repo.ComAndroidKeepass.LogInActivity.FileToSelectInfo, new RecordItemIndex(0));
            repo.ComAndroidKeepass.LogInActivity.FileToSelect.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.LogInActivity.Password' at Center", repo.ComAndroidKeepass.LogInActivity.PasswordInfo, new RecordItemIndex(1));
            repo.ComAndroidKeepass.LogInActivity.Password.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varPassword' on item 'ComAndroidKeepass.LogInActivity.Password'.", repo.ComAndroidKeepass.LogInActivity.PasswordInfo, new RecordItemIndex(2));
            repo.ComAndroidKeepass.LogInActivity.Password.Element.SetAttributeValue("Text", varPassword);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.LogInActivity.PassKeyfile' at Center", repo.ComAndroidKeepass.LogInActivity.PassKeyfileInfo, new RecordItemIndex(3));
            repo.ComAndroidKeepass.LogInActivity.PassKeyfile.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$VarKey' on item 'ComAndroidKeepass.LogInActivity.PassKeyfile'.", repo.ComAndroidKeepass.LogInActivity.PassKeyfileInfo, new RecordItemIndex(4));
            repo.ComAndroidKeepass.LogInActivity.PassKeyfile.Element.SetAttributeValue("Text", VarKey);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComAndroidKeepass.LogInActivity.LoginOk' at Center", repo.ComAndroidKeepass.LogInActivity.LoginOkInfo, new RecordItemIndex(5));
            repo.ComAndroidKeepass.LogInActivity.LoginOk.Touch();
            Delay.Milliseconds(300);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
