///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeePassApplicationTest.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateDatabase recording.
    /// </summary>
    [TestModule("9f330de8-fcc8-48ca-955d-5ed61be04039", ModuleType.Recording, 1)]
    public partial class ValidateDatabase : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::KeePassApplicationTest.KeePassApplicationTestRepository repository.
        /// </summary>
        public static global::KeePassApplicationTest.KeePassApplicationTestRepository repo = global::KeePassApplicationTest.KeePassApplicationTestRepository.Instance;

        static ValidateDatabase instance = new ValidateDatabase();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateDatabase()
        {
            varFileName = "/storage/emulated/0/keepass/keepassNewFile.kdb";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateDatabase Instance
        {
            get { return instance; }
        }

#region Variables

        string _varFileName;

        /// <summary>
        /// Gets or sets the value of variable varFileName.
        /// </summary>
        [TestVariable("1bbdec41-991a-40fe-b935-2e2367117260")]
        public string varFileName
        {
            get { return _varFileName; }
            set { _varFileName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varFileName) on item 'ComAndroidKeepass.HomePage.MostRecentDatabase'.", repo.ComAndroidKeepass.HomePage.MostRecentDatabaseInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ComAndroidKeepass.HomePage.MostRecentDatabaseInfo, "Text", varFileName);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
