///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace KeePassApplicationTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the KeePassApplicationTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e8585637-d901-4164-9561-70f7697835d7")]
    public partial class KeePassApplicationTestRepository : RepoGenBaseFolder
    {
        static KeePassApplicationTestRepository instance = new KeePassApplicationTestRepository();
        KeePassApplicationTestRepositoryFolders.ComAndroidKeepassAppFolder _comandroidkeepass;

        /// <summary>
        /// Gets the singleton class instance representing the KeePassApplicationTestRepository element repository.
        /// </summary>
        [RepositoryFolder("e8585637-d901-4164-9561-70f7697835d7")]
        public static KeePassApplicationTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public KeePassApplicationTestRepository() 
            : base("KeePassApplicationTestRepository", "/", null, 0, false, "e8585637-d901-4164-9561-70f7697835d7", ".\\RepositoryImages\\KeePassApplicationTestRepositorye8585637.rximgres")
        {
            _comandroidkeepass = new KeePassApplicationTestRepositoryFolders.ComAndroidKeepassAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e8585637-d901-4164-9561-70f7697835d7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComAndroidKeepass folder.
        /// </summary>
        [RepositoryFolder("0523ee1b-9366-4c10-ada2-a5e24a0f10df")]
        public virtual KeePassApplicationTestRepositoryFolders.ComAndroidKeepassAppFolder ComAndroidKeepass
        {
            get { return _comandroidkeepass; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class KeePassApplicationTestRepositoryFolders
    {
        /// <summary>
        /// The ComAndroidKeepassAppFolder folder.
        /// </summary>
        [RepositoryFolder("0523ee1b-9366-4c10-ada2-a5e24a0f10df")]
        public partial class ComAndroidKeepassAppFolder : RepoGenBaseFolder
        {
            KeePassApplicationTestRepositoryFolders.CreateDatabaseFolder _createdatabase;
            KeePassApplicationTestRepositoryFolders.GroupActivityFolder _groupactivity;
            KeePassApplicationTestRepositoryFolders.LogInActivityFolder _loginactivity;
            KeePassApplicationTestRepositoryFolders.HomePageFolder _homepage;
            KeePassApplicationTestRepositoryFolders.AddInternetFolder _addinternet;

            /// <summary>
            /// Creates a new ComAndroidKeepass  folder.
            /// </summary>
            public ComAndroidKeepassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComAndroidKeepass", "/mobileapp[@title='com.android.keepass']", parentFolder, 30000, null, false, "0523ee1b-9366-4c10-ada2-a5e24a0f10df", "")
            {
                _createdatabase = new KeePassApplicationTestRepositoryFolders.CreateDatabaseFolder(this);
                _groupactivity = new KeePassApplicationTestRepositoryFolders.GroupActivityFolder(this);
                _loginactivity = new KeePassApplicationTestRepositoryFolders.LogInActivityFolder(this);
                _homepage = new KeePassApplicationTestRepositoryFolders.HomePageFolder(this);
                _addinternet = new KeePassApplicationTestRepositoryFolders.AddInternetFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0523ee1b-9366-4c10-ada2-a5e24a0f10df")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0523ee1b-9366-4c10-ada2-a5e24a0f10df")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateDatabase folder.
            /// </summary>
            [RepositoryFolder("fa9d35bf-026d-454e-98f0-460e8bfa2593")]
            public virtual KeePassApplicationTestRepositoryFolders.CreateDatabaseFolder CreateDatabase
            {
                get { return _createdatabase; }
            }

            /// <summary>
            /// The GroupActivity folder.
            /// </summary>
            [RepositoryFolder("a43ece6a-51bf-46ff-b3d0-f40518a6cc5d")]
            public virtual KeePassApplicationTestRepositoryFolders.GroupActivityFolder GroupActivity
            {
                get { return _groupactivity; }
            }

            /// <summary>
            /// The LogInActivity folder.
            /// </summary>
            [RepositoryFolder("b630047f-5590-4694-9187-249582152dd5")]
            public virtual KeePassApplicationTestRepositoryFolders.LogInActivityFolder LogInActivity
            {
                get { return _loginactivity; }
            }

            /// <summary>
            /// The HomePage folder.
            /// </summary>
            [RepositoryFolder("5b61601c-4fca-4f27-9b7f-fecdfafed6ea")]
            public virtual KeePassApplicationTestRepositoryFolders.HomePageFolder HomePage
            {
                get { return _homepage; }
            }

            /// <summary>
            /// The AddInternet folder.
            /// </summary>
            [RepositoryFolder("a537d4f0-2e77-4293-a565-d4a8fee46ea3")]
            public virtual KeePassApplicationTestRepositoryFolders.AddInternetFolder AddInternet
            {
                get { return _addinternet; }
            }
        }

        /// <summary>
        /// The CreateDatabaseFolder folder.
        /// </summary>
        [RepositoryFolder("fa9d35bf-026d-454e-98f0-460e8bfa2593")]
        public partial class CreateDatabaseFolder : RepoGenBaseFolder
        {
            RepoItemInfo _createbuttonInfo;
            RepoItemInfo _filefilenameInfo;
            RepoItemInfo _passpasswordInfo;
            RepoItemInfo _passconfpasswordInfo;
            RepoItemInfo _passkeyfileInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new CreateDatabase  folder.
            /// </summary>
            public CreateDatabaseFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateDatabase", "", parentFolder, 30000, null, false, "fa9d35bf-026d-454e-98f0-460e8bfa2593", "")
            {
                _createbuttonInfo = new RepoItemInfo(this, "CreateButton", "form[@title='FileSelectActivity']/container[@rid='content']//button[@resourceid='R.string.menu_create']", ".//button[@resourceid='R.string.menu_create']", 30000, null, "3f56b8f0-c5cd-4362-9243-0dab42b7d535");
                _filefilenameInfo = new RepoItemInfo(this, "FileFilename", "form[@title='FileSelectActivity']/container[@rid='content']/?/?/androidelement[@rid='file_select']/container[@containertype='Relative']/text[@rid='file_filename']", ".//androidelement[@rid='file_select']/container[@containertype='Relative']/text[@rid='file_filename']", 30000, null, "0093abb0-c076-4159-a929-4c2e91ca7ce7");
                _passpasswordInfo = new RepoItemInfo(this, "PassPassword", "form[@title='(none)']//text[@rid='pass_password']", ".//text[@rid='pass_password']", 30000, null, "ca43de4c-ca9d-4e8f-a567-14cf8e98c827");
                _passconfpasswordInfo = new RepoItemInfo(this, "PassConfPassword", "form[@title='(none)']//text[@rid='pass_conf_password']", ".//text[@rid='pass_conf_password']", 30000, null, "015b7640-825e-416a-baf2-f0f4b25f726e");
                _passkeyfileInfo = new RepoItemInfo(this, "PassKeyfile", "form[@title='(none)']//text[@rid='pass_keyfile']", ".//text[@rid='pass_keyfile']", 30000, null, "2599291c-bf25-4653-ad6a-97b4c9306b12");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOk", "form[@title='(none)']//button[@resourceid='R.string.yes']", ".//button[@resourceid='R.string.yes']", 30000, null, "6e819924-1030-4420-b611-ec24cad8481b");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "form[@title='(none)']//button[@resourceid='R.string.entry_cancel']", ".//button[@resourceid='R.string.entry_cancel']", 30000, null, "6af0fd2b-8046-4362-88f8-73dbef281417");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fa9d35bf-026d-454e-98f0-460e8bfa2593")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fa9d35bf-026d-454e-98f0-460e8bfa2593")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CreateButton item.
            /// </summary>
            [RepositoryItem("3f56b8f0-c5cd-4362-9243-0dab42b7d535")]
            public virtual Ranorex.Button CreateButton
            {
                get
                {
                    return _createbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateButton item info.
            /// </summary>
            [RepositoryItemInfo("3f56b8f0-c5cd-4362-9243-0dab42b7d535")]
            public virtual RepoItemInfo CreateButtonInfo
            {
                get
                {
                    return _createbuttonInfo;
                }
            }

            /// <summary>
            /// The FileFilename item.
            /// </summary>
            [RepositoryItem("0093abb0-c076-4159-a929-4c2e91ca7ce7")]
            public virtual Ranorex.Text FileFilename
            {
                get
                {
                    return _filefilenameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FileFilename item info.
            /// </summary>
            [RepositoryItemInfo("0093abb0-c076-4159-a929-4c2e91ca7ce7")]
            public virtual RepoItemInfo FileFilenameInfo
            {
                get
                {
                    return _filefilenameInfo;
                }
            }

            /// <summary>
            /// The PassPassword item.
            /// </summary>
            [RepositoryItem("ca43de4c-ca9d-4e8f-a567-14cf8e98c827")]
            public virtual Ranorex.Text PassPassword
            {
                get
                {
                    return _passpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PassPassword item info.
            /// </summary>
            [RepositoryItemInfo("ca43de4c-ca9d-4e8f-a567-14cf8e98c827")]
            public virtual RepoItemInfo PassPasswordInfo
            {
                get
                {
                    return _passpasswordInfo;
                }
            }

            /// <summary>
            /// The PassConfPassword item.
            /// </summary>
            [RepositoryItem("015b7640-825e-416a-baf2-f0f4b25f726e")]
            public virtual Ranorex.Text PassConfPassword
            {
                get
                {
                    return _passconfpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PassConfPassword item info.
            /// </summary>
            [RepositoryItemInfo("015b7640-825e-416a-baf2-f0f4b25f726e")]
            public virtual RepoItemInfo PassConfPasswordInfo
            {
                get
                {
                    return _passconfpasswordInfo;
                }
            }

            /// <summary>
            /// The PassKeyfile item.
            /// </summary>
            [RepositoryItem("2599291c-bf25-4653-ad6a-97b4c9306b12")]
            public virtual Ranorex.Text PassKeyfile
            {
                get
                {
                    return _passkeyfileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PassKeyfile item info.
            /// </summary>
            [RepositoryItemInfo("2599291c-bf25-4653-ad6a-97b4c9306b12")]
            public virtual RepoItemInfo PassKeyfileInfo
            {
                get
                {
                    return _passkeyfileInfo;
                }
            }

            /// <summary>
            /// The ButtonOk item.
            /// </summary>
            [RepositoryItem("6e819924-1030-4420-b611-ec24cad8481b")]
            public virtual Ranorex.Button ButtonOk
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOk item info.
            /// </summary>
            [RepositoryItemInfo("6e819924-1030-4420-b611-ec24cad8481b")]
            public virtual RepoItemInfo ButtonOkInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("6af0fd2b-8046-4362-88f8-73dbef281417")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("6af0fd2b-8046-4362-88f8-73dbef281417")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

        /// <summary>
        /// The GroupActivityFolder folder.
        /// </summary>
        [RepositoryFolder("a43ece6a-51bf-46ff-b3d0-f40518a6cc5d")]
        public partial class GroupActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addgroupInfo;
            RepoItemInfo _groupnameInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new GroupActivity  folder.
            /// </summary>
            public GroupActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("GroupActivity", "", parentFolder, 30000, null, false, "a43ece6a-51bf-46ff-b3d0-f40518a6cc5d", "")
            {
                _addgroupInfo = new RepoItemInfo(this, "AddGroup", "form[@title='GroupActivityV3']/container[@rid='content']//button[@resourceid='R.string.add_group']", ".//button[@resourceid='R.string.add_group']", 30000, null, "4c3a6f2c-fafe-40a6-a001-ae990a67d6b8");
                _groupnameInfo = new RepoItemInfo(this, "GroupName", "form[2]//text[@rid='group_name']", ".//text[@rid='group_name']", 30000, null, "3caf0963-0cf0-4569-a60c-4d40af48b17b");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOk", "form[2]//button[@resourceid='R.string.yes']", ".//button[@resourceid='R.string.yes']", 30000, null, "272faae2-bb80-4b89-9e49-b745f586ea0b");
                _cancelInfo = new RepoItemInfo(this, "Cancel", "form[2]//button[@resourceid='R.string.entry_cancel']", ".//button[@resourceid='R.string.entry_cancel']", 30000, null, "2fd58921-18f7-4c02-844e-1ae72336769d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a43ece6a-51bf-46ff-b3d0-f40518a6cc5d")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a43ece6a-51bf-46ff-b3d0-f40518a6cc5d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddGroup item.
            /// </summary>
            [RepositoryItem("4c3a6f2c-fafe-40a6-a001-ae990a67d6b8")]
            public virtual Ranorex.Button AddGroup
            {
                get
                {
                    return _addgroupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddGroup item info.
            /// </summary>
            [RepositoryItemInfo("4c3a6f2c-fafe-40a6-a001-ae990a67d6b8")]
            public virtual RepoItemInfo AddGroupInfo
            {
                get
                {
                    return _addgroupInfo;
                }
            }

            /// <summary>
            /// The GroupName item.
            /// </summary>
            [RepositoryItem("3caf0963-0cf0-4569-a60c-4d40af48b17b")]
            public virtual Ranorex.Text GroupName
            {
                get
                {
                    return _groupnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GroupName item info.
            /// </summary>
            [RepositoryItemInfo("3caf0963-0cf0-4569-a60c-4d40af48b17b")]
            public virtual RepoItemInfo GroupNameInfo
            {
                get
                {
                    return _groupnameInfo;
                }
            }

            /// <summary>
            /// The ButtonOk item.
            /// </summary>
            [RepositoryItem("272faae2-bb80-4b89-9e49-b745f586ea0b")]
            public virtual Ranorex.Button ButtonOk
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOk item info.
            /// </summary>
            [RepositoryItemInfo("272faae2-bb80-4b89-9e49-b745f586ea0b")]
            public virtual RepoItemInfo ButtonOkInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("2fd58921-18f7-4c02-844e-1ae72336769d")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("2fd58921-18f7-4c02-844e-1ae72336769d")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

        /// <summary>
        /// The LogInActivityFolder folder.
        /// </summary>
        [RepositoryFolder("b630047f-5590-4694-9187-249582152dd5")]
        public partial class LogInActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filetoselectInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _passkeyfileInfo;
            RepoItemInfo _loginokInfo;

            /// <summary>
            /// Creates a new LogInActivity  folder.
            /// </summary>
            public LogInActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("LogInActivity", "", parentFolder, 30000, null, false, "b630047f-5590-4694-9187-249582152dd5", "")
            {
                _filetoselectInfo = new RepoItemInfo(this, "FileToSelect", "form[@title='FileSelectActivity']//list[@rid='list']", ".//list/text[1]", 30000, null, "d8387a34-6560-42db-9f4b-e69a1798a354");
                _passwordInfo = new RepoItemInfo(this, "Password", "form[@title='PasswordActivity']//text[@rid='password']", ".//text[@rid='password']", 30000, null, "e9adb01c-ad86-494f-a7ac-86a3e305b837");
                _passkeyfileInfo = new RepoItemInfo(this, "PassKeyfile", "form[@title='PasswordActivity']//text[@rid='pass_keyfile']", ".//text[@rid='pass_keyfile']", 30000, null, "8ff2c683-7de6-45ad-a988-6f4443f0d669");
                _loginokInfo = new RepoItemInfo(this, "LoginOk", "form[@title='PasswordActivity']//button[@resourceid='R.string.yes']", "element", 30000, null, "5025484b-69f8-4d0d-999b-159dc38bf3dd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b630047f-5590-4694-9187-249582152dd5")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b630047f-5590-4694-9187-249582152dd5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileToSelect item.
            /// </summary>
            [RepositoryItem("d8387a34-6560-42db-9f4b-e69a1798a354")]
            public virtual Ranorex.List FileToSelect
            {
                get
                {
                    return _filetoselectInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The FileToSelect item info.
            /// </summary>
            [RepositoryItemInfo("d8387a34-6560-42db-9f4b-e69a1798a354")]
            public virtual RepoItemInfo FileToSelectInfo
            {
                get
                {
                    return _filetoselectInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("e9adb01c-ad86-494f-a7ac-86a3e305b837")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("e9adb01c-ad86-494f-a7ac-86a3e305b837")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The PassKeyfile item.
            /// </summary>
            [RepositoryItem("8ff2c683-7de6-45ad-a988-6f4443f0d669")]
            public virtual Ranorex.Text PassKeyfile
            {
                get
                {
                    return _passkeyfileInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PassKeyfile item info.
            /// </summary>
            [RepositoryItemInfo("8ff2c683-7de6-45ad-a988-6f4443f0d669")]
            public virtual RepoItemInfo PassKeyfileInfo
            {
                get
                {
                    return _passkeyfileInfo;
                }
            }

            /// <summary>
            /// The LoginOk item.
            /// </summary>
            [RepositoryItem("5025484b-69f8-4d0d-999b-159dc38bf3dd")]
            public virtual Ranorex.Button LoginOk
            {
                get
                {
                    return _loginokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LoginOk item info.
            /// </summary>
            [RepositoryItemInfo("5025484b-69f8-4d0d-999b-159dc38bf3dd")]
            public virtual RepoItemInfo LoginOkInfo
            {
                get
                {
                    return _loginokInfo;
                }
            }
        }

        /// <summary>
        /// The HomePageFolder folder.
        /// </summary>
        [RepositoryFolder("5b61601c-4fca-4f27-9b7f-fecdfafed6ea")]
        public partial class HomePageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mostrecentdatabaseInfo;

            /// <summary>
            /// Creates a new HomePage  folder.
            /// </summary>
            public HomePageFolder(RepoGenBaseFolder parentFolder) :
                    base("HomePage", "", parentFolder, 30000, null, false, "5b61601c-4fca-4f27-9b7f-fecdfafed6ea", "")
            {
                _mostrecentdatabaseInfo = new RepoItemInfo(this, "MostRecentDatabase", "form[@title='FileSelectActivity']//list[@rid='list']/text[1]", ".//list/text[1]", 30000, null, "8fd69d53-d908-4cc0-89ab-5a7cb4ed8089");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5b61601c-4fca-4f27-9b7f-fecdfafed6ea")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5b61601c-4fca-4f27-9b7f-fecdfafed6ea")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MostRecentDatabase item.
            /// </summary>
            [RepositoryItem("8fd69d53-d908-4cc0-89ab-5a7cb4ed8089")]
            public virtual Ranorex.Text MostRecentDatabase
            {
                get
                {
                    return _mostrecentdatabaseInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MostRecentDatabase item info.
            /// </summary>
            [RepositoryItemInfo("8fd69d53-d908-4cc0-89ab-5a7cb4ed8089")]
            public virtual RepoItemInfo MostRecentDatabaseInfo
            {
                get
                {
                    return _mostrecentdatabaseInfo;
                }
            }
        }

        /// <summary>
        /// The AddInternetFolder folder.
        /// </summary>
        [RepositoryFolder("a537d4f0-2e77-4293-a565-d4a8fee46ea3")]
        public partial class AddInternetFolder : RepoGenBaseFolder
        {
            RepoItemInfo _internetInfo;
            RepoItemInfo _addentryInfo;
            RepoItemInfo _addgroupInfo;
            RepoItemInfo _entrytitleInfo;
            RepoItemInfo _entryusernameInfo;
            RepoItemInfo _entryurlInfo;
            RepoItemInfo _entrypasswordInfo;
            RepoItemInfo _entryconfpasswordInfo;
            RepoItemInfo _entrycommentInfo;
            RepoItemInfo _iconbuttonInfo;
            RepoItemInfo _iconInfo;
            RepoItemInfo _entrysaveInfo;
            RepoItemInfo _validatetitleInfo;

            /// <summary>
            /// Creates a new AddInternet  folder.
            /// </summary>
            public AddInternetFolder(RepoGenBaseFolder parentFolder) :
                    base("AddInternet", "", parentFolder, 30000, null, false, "a537d4f0-2e77-4293-a565-d4a8fee46ea3", "")
            {
                _internetInfo = new RepoItemInfo(this, "Internet", "form[@title='GroupActivityV3']/container[@rid='content']//list[@rid='list']/androidelement[2]/table/?/?/text[@caption='Internet']", ".//text[@caption='Internet']", 30000, null, "846f71d6-4a2e-47ce-a1bd-89e70c0edee6");
                _addentryInfo = new RepoItemInfo(this, "AddEntry", "form[@title='GroupActivityV3']/container[@rid='content']//button[@resourceid='R.string.add_entry']", ".//button[@resourceid='R.string.add_entry']", 30000, null, "c0e402d8-cf43-4d3c-8e74-badf210abcb1");
                _addgroupInfo = new RepoItemInfo(this, "AddGroup", "form[@title='GroupActivityV3']/container[@rid='content']//button[@resourceid='R.string.add_group']", "element", 30000, null, "af0a8fd2-4b3c-4902-bd9e-368950ac2057");
                _entrytitleInfo = new RepoItemInfo(this, "EntryTitle", "form[@title='EntryEditActivityV3']/container[@rid='content']//text[@rid='entry_title']", ".//text[@rid='entry_title']", 30000, null, "c4abc8b9-6ce6-4c7e-8f8f-54cb4fcd24a1");
                _entryusernameInfo = new RepoItemInfo(this, "EntryUserName", "form[@title='EntryEditActivityV3']/container[@rid='content']//text[@rid='entry_user_name']", ".//text[@rid='entry_user_name']", 30000, null, "e71b4a19-9c1c-444d-a6e4-1faeba0de925");
                _entryurlInfo = new RepoItemInfo(this, "EntryUrl", "form[@title='EntryEditActivityV3']/container[@rid='content']//text[@rid='entry_url']", ".//text[@rid='entry_url']", 30000, null, "db843c7c-28a9-4dd0-a03c-9fb880df262f");
                _entrypasswordInfo = new RepoItemInfo(this, "EntryPassword", "form[@title='EntryEditActivityV3']/container[@rid='content']//text[@rid='entry_password']", ".//text[@rid='entry_password']", 30000, null, "ec06c0ff-dd54-4e64-ada8-e79e5e0382c2");
                _entryconfpasswordInfo = new RepoItemInfo(this, "EntryConfpassword", "form[@title='EntryEditActivityV3']/container[@rid='content']//text[@rid='entry_confpassword']", ".//text[@rid='entry_confpassword']", 30000, null, "1dc4bb4f-d93e-4457-b82e-382c4a53091e");
                _entrycommentInfo = new RepoItemInfo(this, "EntryComment", "form[@title='EntryEditActivityV3']/container[@rid='content']//text[@rid='entry_comment']", ".//text[@rid='entry_comment']", 30000, null, "22f6283f-22e7-4feb-a13e-3cd1f776dc16");
                _iconbuttonInfo = new RepoItemInfo(this, "IconButton", "form[@title='EntryEditActivityV3']/container[@rid='content']//button[@rid='icon_button']", ".//button[@rid='icon_button']", 30000, null, "6f18d33c-3f7d-4a8a-a2b0-556955439bbd");
                _iconInfo = new RepoItemInfo(this, "Icon", "form[@title='IconPickerActivity']/?/?/container[@rid='IconGridView']/container[12]", ".//container[@rid='IconGridView']/container[12]", 30000, null, "e0966d45-1ae3-4a9c-95d1-ffefb045b8e3");
                _entrysaveInfo = new RepoItemInfo(this, "EntrySave", "form[@title='EntryEditActivityV3']//button[@resourceid='R.string.entry_save']", ".//button[@resourceid='R.string.entry_save']", 30000, null, "bcc29dc5-e4c8-469f-878d-526a61cc3038");
                _validatetitleInfo = new RepoItemInfo(this, "ValidateTitle", "form[@title='GroupActivityV3']/container[@rid='content']//list[@rid='list']/?/?/table/?/?/text", ".//text[@caption='HashedIn']", 30000, null, "1ed07df3-d08a-41ce-bdfd-ae4ead635d74");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a537d4f0-2e77-4293-a565-d4a8fee46ea3")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a537d4f0-2e77-4293-a565-d4a8fee46ea3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Internet item.
            /// </summary>
            [RepositoryItem("846f71d6-4a2e-47ce-a1bd-89e70c0edee6")]
            public virtual Ranorex.Text Internet
            {
                get
                {
                    return _internetInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Internet item info.
            /// </summary>
            [RepositoryItemInfo("846f71d6-4a2e-47ce-a1bd-89e70c0edee6")]
            public virtual RepoItemInfo InternetInfo
            {
                get
                {
                    return _internetInfo;
                }
            }

            /// <summary>
            /// The AddEntry item.
            /// </summary>
            [RepositoryItem("c0e402d8-cf43-4d3c-8e74-badf210abcb1")]
            public virtual Ranorex.Button AddEntry
            {
                get
                {
                    return _addentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddEntry item info.
            /// </summary>
            [RepositoryItemInfo("c0e402d8-cf43-4d3c-8e74-badf210abcb1")]
            public virtual RepoItemInfo AddEntryInfo
            {
                get
                {
                    return _addentryInfo;
                }
            }

            /// <summary>
            /// The AddGroup item.
            /// </summary>
            [RepositoryItem("af0a8fd2-4b3c-4902-bd9e-368950ac2057")]
            public virtual Ranorex.Button AddGroup
            {
                get
                {
                    return _addgroupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddGroup item info.
            /// </summary>
            [RepositoryItemInfo("af0a8fd2-4b3c-4902-bd9e-368950ac2057")]
            public virtual RepoItemInfo AddGroupInfo
            {
                get
                {
                    return _addgroupInfo;
                }
            }

            /// <summary>
            /// The EntryTitle item.
            /// </summary>
            [RepositoryItem("c4abc8b9-6ce6-4c7e-8f8f-54cb4fcd24a1")]
            public virtual Ranorex.Text EntryTitle
            {
                get
                {
                    return _entrytitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryTitle item info.
            /// </summary>
            [RepositoryItemInfo("c4abc8b9-6ce6-4c7e-8f8f-54cb4fcd24a1")]
            public virtual RepoItemInfo EntryTitleInfo
            {
                get
                {
                    return _entrytitleInfo;
                }
            }

            /// <summary>
            /// The EntryUserName item.
            /// </summary>
            [RepositoryItem("e71b4a19-9c1c-444d-a6e4-1faeba0de925")]
            public virtual Ranorex.Text EntryUserName
            {
                get
                {
                    return _entryusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryUserName item info.
            /// </summary>
            [RepositoryItemInfo("e71b4a19-9c1c-444d-a6e4-1faeba0de925")]
            public virtual RepoItemInfo EntryUserNameInfo
            {
                get
                {
                    return _entryusernameInfo;
                }
            }

            /// <summary>
            /// The EntryUrl item.
            /// </summary>
            [RepositoryItem("db843c7c-28a9-4dd0-a03c-9fb880df262f")]
            public virtual Ranorex.Text EntryUrl
            {
                get
                {
                    return _entryurlInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryUrl item info.
            /// </summary>
            [RepositoryItemInfo("db843c7c-28a9-4dd0-a03c-9fb880df262f")]
            public virtual RepoItemInfo EntryUrlInfo
            {
                get
                {
                    return _entryurlInfo;
                }
            }

            /// <summary>
            /// The EntryPassword item.
            /// </summary>
            [RepositoryItem("ec06c0ff-dd54-4e64-ada8-e79e5e0382c2")]
            public virtual Ranorex.Text EntryPassword
            {
                get
                {
                    return _entrypasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryPassword item info.
            /// </summary>
            [RepositoryItemInfo("ec06c0ff-dd54-4e64-ada8-e79e5e0382c2")]
            public virtual RepoItemInfo EntryPasswordInfo
            {
                get
                {
                    return _entrypasswordInfo;
                }
            }

            /// <summary>
            /// The EntryConfpassword item.
            /// </summary>
            [RepositoryItem("1dc4bb4f-d93e-4457-b82e-382c4a53091e")]
            public virtual Ranorex.Text EntryConfpassword
            {
                get
                {
                    return _entryconfpasswordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryConfpassword item info.
            /// </summary>
            [RepositoryItemInfo("1dc4bb4f-d93e-4457-b82e-382c4a53091e")]
            public virtual RepoItemInfo EntryConfpasswordInfo
            {
                get
                {
                    return _entryconfpasswordInfo;
                }
            }

            /// <summary>
            /// The EntryComment item.
            /// </summary>
            [RepositoryItem("22f6283f-22e7-4feb-a13e-3cd1f776dc16")]
            public virtual Ranorex.Text EntryComment
            {
                get
                {
                    return _entrycommentInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EntryComment item info.
            /// </summary>
            [RepositoryItemInfo("22f6283f-22e7-4feb-a13e-3cd1f776dc16")]
            public virtual RepoItemInfo EntryCommentInfo
            {
                get
                {
                    return _entrycommentInfo;
                }
            }

            /// <summary>
            /// The IconButton item.
            /// </summary>
            [RepositoryItem("6f18d33c-3f7d-4a8a-a2b0-556955439bbd")]
            public virtual Ranorex.Button IconButton
            {
                get
                {
                    return _iconbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The IconButton item info.
            /// </summary>
            [RepositoryItemInfo("6f18d33c-3f7d-4a8a-a2b0-556955439bbd")]
            public virtual RepoItemInfo IconButtonInfo
            {
                get
                {
                    return _iconbuttonInfo;
                }
            }

            /// <summary>
            /// The Icon item.
            /// </summary>
            [RepositoryItem("e0966d45-1ae3-4a9c-95d1-ffefb045b8e3")]
            public virtual Ranorex.Container Icon
            {
                get
                {
                    return _iconInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Icon item info.
            /// </summary>
            [RepositoryItemInfo("e0966d45-1ae3-4a9c-95d1-ffefb045b8e3")]
            public virtual RepoItemInfo IconInfo
            {
                get
                {
                    return _iconInfo;
                }
            }

            /// <summary>
            /// The EntrySave item.
            /// </summary>
            [RepositoryItem("bcc29dc5-e4c8-469f-878d-526a61cc3038")]
            public virtual Ranorex.Button EntrySave
            {
                get
                {
                    return _entrysaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EntrySave item info.
            /// </summary>
            [RepositoryItemInfo("bcc29dc5-e4c8-469f-878d-526a61cc3038")]
            public virtual RepoItemInfo EntrySaveInfo
            {
                get
                {
                    return _entrysaveInfo;
                }
            }

            /// <summary>
            /// The ValidateTitle item.
            /// </summary>
            [RepositoryItem("1ed07df3-d08a-41ce-bdfd-ae4ead635d74")]
            public virtual Ranorex.Text ValidateTitle
            {
                get
                {
                    return _validatetitleInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ValidateTitle item info.
            /// </summary>
            [RepositoryItemInfo("1ed07df3-d08a-41ce-bdfd-ae4ead635d74")]
            public virtual RepoItemInfo ValidateTitleInfo
            {
                get
                {
                    return _validatetitleInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
